version: '2'
services:
  web:
    build: .
    command: bundle exec unicorn -E production -c config/unicorn.rb
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - .:/app     
    depends_on:
      - db
    links:
      - db
    environment:
     # MYSQL_HOST:db
     # MYSQL_USER: root
     # MYSQL_PASSWORD: password
     # MYSQL_PORT: 3306
     SECRET_KEY_BASE: 'h6rbZUsoTLMxX7dvLUto;s8NGy8HyU4mPis8cyoNmpPckvgZ,V'
     RAILS_ENV: development
     # SDC_SENDGRID_API_KEY
     # SDC_SENDGRID_FROM
     # SDC_SENDGRID_APPROVETEMPLATE
      
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    #environment:
     # MYSQL_ROOT_PASSWORD: password
     # MYSQL_DATABASE: dbadmin

 
  # db:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #   volumes:
  #     - /Users/vz/steemit/mysql-data:/var/lib/mysql
  # proxy:
  #   image: jwilder/nginx-proxy:latest
  #   ports:
  #     - "127.0.0.1:48444:80"
  #   volumes:
  #     - "/var/run/docker.sock:/tmp/docker.sock"
